export const MINGLANILLA_BARANGAYS = [
  'Tulay',
  'Tunghaan',
  'Tungkop',
  'Tungkil',
  'Vito',
  'Ward I',
  'Ward II',
  'Ward III',
  'Ward IV',
  'Cajel',
  'Calajoan',
  'Camp 8',
  'Cuanos',
  'Dakutan',
  'Guindaruhan',
  'Lipata',
  'Manduang',
  'Pakigne',
  'Poblacion Ward I',
  'Poblacion Ward II',
  'Poblacion Ward III',
  'Poblacion Ward IV',
];

