export const MINGLANILLA_BARANGAYS = [
  'Tulay',
  'Tunghaan',
  'Tungkop',
  'Tungkil',
  'Vito',
  'Linao',
  'Cajel',
  'Calajoan',
  'Camp 8',
  'Cuanos',
  'Dakutan',
  'Guindaruhan',
  'Lipata',
  'Manduang',
  'Pakigne',
  'Poblacion Ward 1',
  'Poblacion Ward 2',
  'Poblacion Ward 3',
  'Poblacion Ward 4',
];
